version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: 
            context: nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes_from:
            - php
        cap_add: 
            - ALL
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./nginx/crt:/usr/local/openresty/nginx/conf/crt
            - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    adminer:
        image: adminer
        ports:
            - 8080:8080
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
